GET http://172.16.1.120:5000/products

###
GET http://172.16.1.120:5000/products/1

###
POST http://172.16.1.120:5000/products
Content-Type: application/json

{
	"name": "Product 3",
	"price": 5500
}

###
PATCH http://172.16.1.120:5000/products/1
Content-Type: application/json

{
	"name": "Product 1 - UPDATE",
	"price": 3000
}

###
DELETE http://172.16.1.120:5000/products/3